# Generated by Django 4.2.2 on 2023-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_gd',
            field=models.ImageField(blank=True, null=True, upload_to='productos/gd'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_md',
            field=models.ImageField(blank=True, null=True, upload_to='productos/md'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_pq',
            field=models.ImageField(blank=True, null=True, upload_to='productos/pq'),
        ),
    ]
