# Generated by Django 4.2.2 on 2023-06-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_foto_producto_foto_gd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='noticias')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_gd',
            field=models.ImageField(upload_to='productos/gd'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_md',
            field=models.ImageField(upload_to='productos/md'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_pq',
            field=models.ImageField(upload_to='productos/pq'),
        ),
    ]
