# Generated by Django 4.2.2 on 2023-06-28 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_noticia_alter_producto_foto_gd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='id_boleta',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='id_producto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
    ]
