# Generated by Django 4.2.2 on 2023-06-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_detalleboleta_id_boleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('foto_pq', models.ImageField(upload_to='videojuego/portada/pq')),
                ('foto_md', models.ImageField(upload_to='videojuego/portada/md')),
                ('foto_gd', models.ImageField(upload_to='videojuego/portada/gd')),
                ('id_usuario', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
