# Generated by Django 4.2.2 on 2023-06-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_videojuego_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='estudio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.estudio'),
            preserve_default=False,
        ),
    ]
