# Generated by Django 4.2.2 on 2023-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_videojuego_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='id_usuario',
        ),
    ]
