# Generated by Django 4.2.2 on 2023-06-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_videojuego_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
