# Generated by Django 4.2.2 on 2023-06-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_videojuego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
