# Generated by Django 4.2.2 on 2023-06-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
            preserve_default=False,
        ),
    ]
