# Generated by Django 4.2.2 on 2023-06-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_videojuego_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
