# Generated by Django 4.2.2 on 2023-07-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_esbr_pegi'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='esbr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.esbr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videojuego',
            name='pegi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.pegi'),
            preserve_default=False,
        ),
    ]
