# Generated by Django 4.2.2 on 2023-07-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_videojuego_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
