# Generated by Django 4.2.2 on 2023-07-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alter_videojuego_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
