# Generated by Django 4.2.2 on 2023-07-12 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0023_remove_compra_titulo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('usuario', 'videojuego')},
        ),
    ]
