# Generated by Django 4.2.2 on 2023-07-12 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_alter_compra_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
