# Generated by Django 4.2.2 on 2023-07-12 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_compra_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
